### PR TITLE
Backport to php version 7.1

### PR DESCRIPTION
**Pull request by djschilling**
In my project we still have to use php 7.1.

So i switched the php version to 7.1 and fixed every line that was not compatible.

### CODE REVIEW

**Comment by Gummibeer** [comment]
Hey,

thanks for your work! But I won't accept/merge this. PHP 7.1 is end of life. Even PHP 7.2 is in security only phase.
So I really and only can highly recommend you to upgrade your PHP installation! 🆙
And because I'm a big fan of stricter type system in PHP dropping them to support an outdated version is not part of my roadmap.

For sure you are free to fork if you can't upgrade! Even if I don't recommend to stick with an EOL version. Primary because not much, backward incompatible, has changed in 7.2.
https://www.php.net/manual/en/migration72.php

**Comment by djschilling** [comment]
We will update quite soon to PHP Version 7.2.

Would you accept a mr for 7.2?

**Comment by Gummibeer** [comment]
I'm willing to do something strange for you.
I will create a `v0.3.0-rc.php72`.
I don't plan to upgrade anything regarding functionality in near future.

This release will be a one-time thing. So it's like a pinned version.
All coming releases will still be based on PHP 7.4 so you should still plan to upgrade to latest versions.
If you use Laravel I can recommend you to use https://laravelshift.com/ which does the most painful upgrade tasks automatically. 🎉

I will link the release if it's done.

**Comment by djschilling** [comment]
thanks.

**Comment by Gummibeer** [comment]
Hey,

sorry for the mind-change. 😂
I've done the PHP 7.2 backport and tried running it with 7.1 - no issues. So in fact there isn't a real reason to drop a version only because it's EOL if the code doesn't have to change to support it.
So I've merged your PR, reduced the doc-blocks to single-line ones and added the new supported versions to the test runner setup - everything green.

So here is your `v0.4.0` release supporting `^7.1`. 😉
https://github.com/Astrotomic/php-open-graph/releases/tag/0.4.0

**Comment by djschilling** [comment]
perfect.

**Pull request merged**
